#!/usr/bin/env ruby -x

require "rubygems"
require 'optparse'
require_relative 'src/demo.rb'

Version = "1.0.0"

user_args = {}
opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage example for for running demo task number 1: \n./combo -t 1"
  opt.separator  ""

  opt.on("-t", "--task TASK", Integer, "number of demo task to run") do |task|
    user_args[:task] = task
  end
  opt.on("-f", "--file FILENAME", String, "filename of graph file within folder data/") do |filename|
    user_args[:filename] = filename
  end

  opt.on_tail("-l", "--list", "Lists all currently available demo task numbers") do
    puts "1: BFS and DFS graph traversal demo. \nNotice that, when passing a non-existing task number, demo task 1 will be loaded."
    exit
  end

  opt.on_tail("-h", "--help", "Show this message") do
    puts opt
    exit
  end
  opt.on_tail("--version", "Show version") do
    puts "Combo v#{Version}"
    exit
  end

end
begin
  opt_parser.parse!
  required_args = [:task]
  required_args.each do |arg|
    raise OptionParser::MissingArgument if user_args[arg].nil?
  end

rescue OptionParser::MissingArgument
  puts "Incorrect input argument(s) passed\n"
  puts opt_parser.help
  exit
end

Demo.new(user_args)